config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :students
  root 'home#index'

  get 'home/about'
  # get 'home/index'
  
  get 'search', to: 'students#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :student 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /students or /students.json
  def index
    @students = Student.all
  end
  # GET /students/1 or /students/1.json
  def show
  end
  
  # GET /students/new
  def new
    # @student = Student.new
    @student = current_user.student.build
  end
  
  # GET /students/1/edit
  def edit
  end

  def search
    @student = Student.where("first_name LIKE ?", "%" + params[:q] + "%")
  end
  
  # POST /students or /students.json
  def create
    # @student = Student.new(student_params)
    @student = current_user.student.build(student_params)
    
    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @student = current_user.student.find_by(id: params[:id])
    redirect_to student_path, notice: "Not Authorized" if @student.nil?
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end
  
  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:first_name, :last_name, :phone, :course, :email, :user_id)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
  <%= image_tag("mit.jpg", class: "img-responsive", id: "navbar-logo")%>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
  <li class="nav-item">
          <%= link_to 'Home', root_path, class:'nav-link active' %>
        
        </li>
        <li class="nav-item">
            <%= link_to 'About', home_about_path, class:'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, class:'nav-link', method: :delete  %>
          </li>
          <li class="nav-item">
              <%= link_to 'Edit Profile',  edit_user_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Students', students_path, class:'nav-link' %>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Services
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Bulk SMS</a></li>
                <li><a class="dropdown-item" href="#">Web Programming</a></li>
                <li><a class="dropdown-item" href="#">Project Management</a></li>
                <li><a class="dropdown-item" href="#">Accounting Course</a></li>
                <li><a class="dropdown-item" href="#">ICT Course</a></li>
                <li><a class="dropdown-item" href="#">Computer Packages</a></li>
                <li><a class="dropdown-item" href="#">Customer Services</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Jion Us</a></li>
              </ul>
            </li>
        <% else %>
          <li class="nav-item">
          
              <%= link_to 'Sign In', new_user_session_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
          </li>
      </ul>
        <% end %>

      <form class="d-flex" action="/search">
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h2>About Page</h2> 

app/views/home/index.html.erb
<h1>MIT</h1>
<p>This is a organization for coding</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Trone | Friends ~ App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form|  %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h6><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h6>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder:"FirstName" %><br>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class: "form-control", placeholder:"LastName" %><br>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class: "form-control", placeholder:"Phone" %><br>
  </div>

  <div class="field form-group">

    <%= form.text_field :course , class: "form-control", placeholder:"Course"%><br>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class: "form-control" , placeholder:"Email"%><br>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :student_user_id, class: "form-control" , value: current_user.id , type: :hidden %><br>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= student.course %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>
<table class="table  table-bordered table-hover">
 <h6>Students</h6>
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone</th>
      <th>Course</th>
      <th>Email</th>
      <th>Created_at</th>
      <th>User_id</th> 
      <th colpan="3"></th>    
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.id %></td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.phone %></td>
        <td><%= student.course %></td>
        <td><%= student.email %></td>
        <td><%= student.created_at %></td>
        <td><%= student.user_id %></td>
        <td><%= link_to 'Show' %></td>
        <td><%= link_to 'Edit' %></td>
        <td><%= link_to 'Destroy' %></td>


      </tr>
     
            
    <% end %>
    </tr>   
  </tbody>
</table>
<%= link_to "New student", new_student_path, class:"btn btn-secondary" %> 

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student, class: "btn btn-primary" %>

<br>

<div>
  <%= link_to "Back to students", students_path, class: "btn btn-dark" %>
</div>

app/views/students/search.html.erb
<h5>Searched Results :</h5>
<%= render @student %>

app/views/students/show.html.erb
<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>